name: typed_json_getters
description: A Dart library providing type-safe getters for JSON maps with robust error handling.
version: 0.0.3
repository: https://github.com/ristocloud-group/app-lib-typed-json-getters

environment:
  sdk: ^3.5.2


dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
